### ISSUE TITLE
UnsupportedOperationException: The method getUniqueId is not supported for temporary players.

### ISSUE THREAD

**Issue by FreeMonoid** [Spottedleaf/PacketLimiter#1]
```
[15:56:07] [Netty Server IO #3/ERROR]: [PacketLimiter] Unhandled exception occured in onPacketReceiving(PacketEvent) for PacketLimiter
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$9203f31c.getUniqueId(<generated>) ~[?:?]
	at ca.spottedleaf.packetlimiter.PacketListener.onPacketReceiving(PacketListener.java:65) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:506) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at protocolsupport.protocol.ConnectionImpl.writeServerboundPacket(ConnectionImpl.java:294) ~[?:?]
	at protocolsupport.protocol.ConnectionImpl$ServerboundPacketProcessor.read0(ConnectionImpl.java:373) ~[?:?]
	at protocolsupport.protocol.ConnectionImpl$ServerboundPacketProcessor.process(ConnectionImpl.java:405) ~[?:?]
	at protocolsupport.protocol.ConnectionImpl.readServerboundPackets(ConnectionImpl.java:259) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.java:32) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:21) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:9) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:43) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.14.4.jar:git-Paper-"a8c5e0f2"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[15:56:07] [Netty Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload@6c2bf623[
    tag=minecraft:register
    data=PooledUnsafeDirectByteBuf(ridx: 0, widx: 29, cap: 29)
  ]
```

Happened just once since installing the plugin 3 days ago so looks like just a weird timing edgecase? Player was logging in as usual, subsequent login went without any issues.

**Comment by FreeMonoid** [comment]
Also ran into an NPE on the same line ([PacketListener.java:65](https://github.com/Spottedleaf/PacketLimiter/blob/4b7ef1a25c5c0bd6ab07c1fb5bcc8ef179838e53/src/main/java/ca/spottedleaf/packetlimiter/PacketListener.java#L65)):

```
[01:08:03] [Netty Server IO #0/ERROR]: [PacketLimiter] Unhandled exception occured in onPacketReceiving(PacketEvent) for PacketLimiter
java.lang.NullPointerException: null
	at ca.spottedleaf.packetlimiter.PacketListener.onPacketReceiving(PacketListener.java:65) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:506) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:245) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at protocolsupport.protocol.ConnectionImpl.writeServerboundPacket(ConnectionImpl.java:294) ~[?:?]
	at protocolsupport.protocol.ConnectionImpl$ServerboundPacketProcessor.read0(ConnectionImpl.java:373) ~[?:?]
	at protocolsupport.protocol.ConnectionImpl$ServerboundPacketProcessor.process(ConnectionImpl.java:405) ~[?:?]
	at protocolsupport.protocol.ConnectionImpl.readServerboundPackets(ConnectionImpl.java:259) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.java:32) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:21) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:9) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.14.4.jar:git-Paper-"1832d799"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[01:08:03] [Netty Server IO #0/ERROR]: Parameters: 
  net.minecraft.server.v1_14_R1.PacketPlayInWindowClick@29567151[
    a=0
    slot=0
    button=0
    d=0
    item=1 writable_book
    shift=PICKUP
  ]
```

Not sure if it's the same or related issue, or if you would like a separate report for it.

Player might have had a bad connection as they've re-logged several times; couple other players who normally have good connection with the server also logged out shortly after — not sure if it was a transit issue at the time or whatever this player did caused that.

**Comment by Spottedleaf** [comment]
I pushed a change that should resolve this - will put the jar up on spigotmc soon

**Comment by Spottedleaf** [comment]
please try latest

**Comment by FreeMonoid** [comment]
Thank you! I'll let it run for a couple of days and will update this issue

**Comment by alec-jensen** [comment]
Hey, I am getting this issue on my server.
