### ISSUE TITLE
Plugin disables on start in Paper 1.18.2

### ISSUE THREAD

**Issue by CloudeLecaw** [Spottedleaf/PacketLimiter#4]
Maybe its because of the New Protocloblib 5..0.0....

```
[02:17:18 INFO]: [PacketLimiter] Enabling PacketLimiter v1.0.0
[02:17:18 ERROR]: [Minecraft] Error occurred while enabling PacketLimiter v1.0.0 (Is it up to date?)
java.lang.NoSuchFieldError: INTERCEPT_INPUT_BUFFER
        at ca.spottedleaf.packetlimiter.PacketListener.<init>(PacketListener.java:34) ~[PacketLimiter_1.0.1.jar:?]
        at ca.spottedleaf.packetlimiter.PacketLimiter.onEnable(PacketLimiter.java:53) ~[PacketLimiter_1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-241]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-241]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-241]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:17:18 INFO]: [PacketLimiter] Disabling PacketLimiter v1.0.0
```

Ok after changing back to Protocollib 4.8.0_Build547 (Relased Version 4.8) i can confirm now that this is because of the new Protocollib Version 5.0.0
https://ci.dmulloy2.net/job/ProtocolLib/551/

Note: plugin.yml tells us its Version 1.0.0 even this is version 1.0.1

**Comment by MWHunter** [comment]
This plugin is not needed with Paper 1.18.  Paper already has this packet limiter built in.

**Comment by CloudeLecaw** [comment]
Well i thought this sticked was closed allready because  the info was also given on procollib site that its not needed anymore
well.. sorry i close it now.
