### ISSUE TITLE
Cannot Loaded PacketLimiter1.0.1.jar

### ISSUE THREAD

**Issue by epsseniyer** [Spottedleaf/PacketLimiter#5]

**Comment by RealmiRoblox** [comment]
[04:55:38 INFO]: [PacketLimiter] Enabling PacketLimiter v1.0.0
[04:55:38 ERROR]: Error occurred while enabling PacketLimiter v1.0.0 (Is it up to date?)
[04:55:38 ERROR]: Suspected Plugins: 
[04:55:38 ERROR]:       PacketLimiter{enabled,ver=1.0.0,path=plugins/packetlimiter-1.0.1.jar}
[04:55:38 ERROR]: Exception details below: 
java.lang.NoSuchFieldError: INTERCEPT_INPUT_BUFFER
        at ca.spottedleaf.packetlimiter.PacketListener.<init>(PacketListener.java:34) ~[?:?]
        at ca.spottedleaf.packetlimiter.PacketLimiter.onEnable(PacketLimiter.java:53) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:319) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Patina-ver/1.16.5-"667fb1b"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
